data:
  batch_size: 3
  database_dir: data/database
  delay_between_batches: 10
  delay_between_requests: 2
  delay_between_tickers: 5
  processed_dir: data/processed
  raw_dir: data/raw
  start_date: '2020-01-01'
  tickers:
  - VIB
  - VCB
  - BID
  - MBB
  - TCB
  - VPB
  - CTG
  - ACB
  - SHB
  - STB
  - HDB
features:
  banking_specific:
  - NIM (%)
  - NPL (%)
  - CIR (%)
  - Provision_Coverage (%)
  - Cost_of_Funds (%)
  - Equity_Ratio (%)
  - Loan_to_Deposit (%)
  - Credit_Growth (%)
  - Pre_Provision_ROA (%)
  - Post_Tax_ROA (%)
  - Non_Interest_Income (%)
  - Loan_to_Asset (%)
  - NPL_to_Asset (%)
  - NIM_Diff
  - NPL_Diff
  - CIR_Diff
  - Credit_Growth_Diff
  fundamental:
  - ROE (%)
  - ROA (%)
  - P/E
  - P/B
  - BVPS (VND)
  - ROE_Diff
  - P_E_Diff
  - PE_to_Close
  direction_threshold: 0.0
  market:
  - Market_Avg_Close
  - Market_Volatility
  technical:
  - Open
  - High
  - Low
  - Close
  - Volume
  - Close_MA7
  - Close_MA14
  - Close_MA30
  - Volatility_14
  - Close_to_Open
  - High_to_Low
  - Close_Pct_Change
  - RSI_14
models:
  # Các tham số dùng chung cho tất cả model
  shared:
    num_classes: 2
    forecast_horizons: [1, 3, 5]

  # Cấu hình cho từng model cụ thể
  cnn_bilstm:
    dropout_rate: 0.5
    hidden_dim: 128       # <<< THAY ĐỔI: Tăng từ 64 lên 128
    kernel_size: 3
    num_layers: 2
  
  transformer:
    d_model: 128          # <<< THAY ĐỔI: Tăng từ 64 lên 128
    dim_feedforward: 256  # <<< THAY ĐỔI: Tăng từ 128 lên 256
    dropout_rate: 0.2
    nhead: 4
    num_layers: 2

paths:
  models: models/
  outputs: outputs/
  processed: data/processed/
  database: data/database/

training:
  batch_size: 32
  epochs: 100 
  early_stopping_patience: 20 # <<< THAY ĐỔI: Tăng từ 15 lên 20
  timesteps: 30
  train_split: 0.8
  val_split: 0.1
  scaler_type: minmax
  
  learning_rate: 0.001      # <<< THAY ĐỔI: Tăng từ 0.0001 lên 0.001

  loss_weights:
    classification: 1.0
    regression: 0.0

#config for prediction quarterly
training_quarterly:
  # Đây là config cho Nhánh 2 (Hàng quý)
  timesteps: 4
  epochs: 100
  batch_size: 4
  learning_rate: 0.001
  early_stopping_patience: 15
  val_split: 0.2