data:
  batch_size: 3
  database_dir: data/database
  delay_between_batches: 10
  delay_between_requests: 2
  delay_between_tickers: 5
  processed_dir: data/processed
  raw_dir: data/raw
  start_date: '2020-01-01'
  tickers:
  - VIB
  - VCB
  - BID
  - MBB
  - TCB
  - VPB
  - CTG
  - ACB
  - SHB
  - STB
  - HDB
features:
  banking_specific:
  - NIM (%)
  - NPL (%)
  - CIR (%)
  - Provision_Coverage (%)
  - Cost_of_Funds (%)
  - Equity_Ratio (%)
  - Loan_to_Deposit (%)
  - Credit_Growth (%)
  - Pre_Provision_ROA (%)
  - Post_Tax_ROA (%)
  - Non_Interest_Income (%)
  - Loan_to_Asset (%)
  - NPL_to_Asset (%)
  - NIM_Diff
  - NPL_Diff
  - CIR_Diff
  - Credit_Growth_Diff
  fundamental:
  - ROE (%)
  - ROA (%)
  - P/E
  - P/B
  - BVPS (VND)
  - ROE_Diff
  - P_E_Diff
  - PE_to_Close
  market:
  - Market_Avg_Close
  - Market_Volatility
  technical:
  - Open
  - High
  - Low
  - Close
  - Volume
  - Close_MA7
  - Close_MA14
  - Close_MA30
  - Volatility_14
  - Close_to_Open
  - High_to_Low
  - Close_Pct_Change
  - RSI_14
models:
  cnn_bilstm:
    dropout_rate: 0.5
    hidden_dim: 64
    kernel_size: 3
    num_layers: 2
  forecast_horizons:
  - 1
  - 3
  - 5
  transformer:
    d_model: 64
    dim_feedforward: 128
    dropout_rate: 0.2
    nhead: 4
    num_layers: 2
paths:
  models_dir: models
  outputs_dir: outputs
training:
  batch_size: 32
  early_stopping_patience: 15  # Increased for focal loss convergence
  epochs: 50
  scaler_type: minmax
  task: regression
  test_split: 0.1
  timesteps: 30
  train_split: 0.8
  val_split: 0.1
  # Enhanced training parameters for focal loss
  focal_loss_alpha: 1.0
  focal_loss_gamma: 2.0
  classification_loss_weight: 2.0  # Emphasis on classification
  regression_loss_weight: 1.0
